export const QUEUE_NAMES = {
  CATEGORIES: 'categories.queue',
  PRODUCTS: 'products.queue',
  REPORTS: 'reports.queue',
  NODES: 'nodes.queue',
  MODELS: 'models.queue',
  DEPLOYMENTS: 'deployments.queue',
  AGENTS: 'agents.queue',
  TOOLS: 'tools.queue',
  CONVERSATIONS: 'conversations.queue',
  MESSAGES: 'messages.queue',
};

export const QUEUE_EVENTS = {
  CATEGORY_CREATED: 'category.created',
  CATEGORY_UPDATED: 'category.updated',
  CATEGORY_DELETED: 'category.deleted',
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_DELETED: 'product.deleted',
  REPORT_GENERATE: 'report.generate',
  NODE_CREATED: 'node.created',
  NODE_UPDATED: 'node.updated',
  NODE_DELETED: 'node.deleted',
  MODEL_CREATED: 'model.created',
  MODEL_UPDATED: 'model.updated',
  MODEL_DELETED: 'model.deleted',
  DEPLOYMENT_CREATED: 'deployment.created',
  DEPLOYMENT_UPDATED: 'deployment.updated',
  DEPLOYMENT_DELETED: 'deployment.deleted',
  DEPLOYMENT_STARTED: 'deployment.started',
  DEPLOYMENT_STOPPED: 'deployment.stopped',
  AGENT_CREATED: 'agent.created',
  AGENT_UPDATED: 'agent.updated',
  AGENT_DELETED: 'agent.deleted',
  TOOL_CREATED: 'tool.created',
  TOOL_UPDATED: 'tool.updated',
  TOOL_DELETED: 'tool.deleted',
  CONVERSATION_CREATED: 'conversation.created',
  CONVERSATION_UPDATED: 'conversation.updated',
  CONVERSATION_DELETED: 'conversation.deleted',
  MESSAGE_CREATED: 'message.created',
  MESSAGE_UPDATED: 'message.updated',
  MESSAGE_DELETED: 'message.deleted',
};
